Add tabs and header menu to pages
js-tasks-ru/htmlcss-20230911-4_xelaris pull request #24
Opened 2023-10-10 20:24 UTC by alexey-ryabkov

2023-10-10 20:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-14 19:55 UTC, GSemikozov requested changes

2023-10-14 19:55 UTC, GSemikozov commented on components/componentDetail/componentDetail.css
> +.componentDetail__tabs .tabs__content {
опять из элемента одного блока залазим в элемент другого) так нельзя.

2023-10-14 19:55 UTC, GSemikozov commented on components/componentDetail/componentDetail.css
> +.componentDetail__tabs .tabs__content::before {
и тут

2023-10-14 19:55 UTC, GSemikozov commented on components/previewCards/previewCards.css
> +.previewCards__tabs .tabs__content {
и тут

2023-10-15 12:43 UTC, GSemikozov approved these changes

2023-10-15 12:43 UTC, merged