Add components pages, setup navigation between
js-tasks-ru/htmlcss-20230911-4_xelaris pull request #34
Opened 2023-10-22 19:57 UTC by alexey-ryabkov

2023-10-22 19:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-31 09:12 UTC, GSemikozov requested changes

2023-10-31 09:12 UTC, GSemikozov commented on components/compPreviews/compPreviews.css
> +.compPreviews__previewSkeleton {
не напасемся под каждый встраиваемый блок создавать свой класс) на уровне превьюхи должен быть общий контейнер, а если надо делать специфические модификации самих встраиваемых блоков - то лучше через модификаторы этих блоков, все-таки дело о внутренней реализации

2023-10-31 09:12 UTC, GSemikozov commented on components/componentDetail/componentDetail.css
> +.componentDetail__button {
отсюда и ниже - см коммент выше

2023-11-01 21:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-02 07:48 UTC, GSemikozov approved these changes

2023-11-02 07:48 UTC, merged