Add button component
js-tasks-ru/htmlcss-20230911-4_xelaris pull request #6
Opened 2023-09-21 08:19 UTC by alexey-ryabkov

2023-09-21 08:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-21 20:31 UTC, GSemikozov requested changes

2023-09-21 20:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
лишнее ограничение - ширина определяется внутренним содержимым

2023-09-21 20:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 2px 8px;
а почему такие маленькие?) `15 15 14`

2023-09-21 20:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--var_primary {
.button_primary и ниже по аналогии

2023-09-21 20:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
лишнее (при pointer-events: none; курсор такой и будет)

2023-09-21 20:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  color: var(--grey-3, #acb5bd);
лишнее

2023-09-22 06:37 UTC, alexey-ryabkov commented on 03-lection1/01-button/button.css
> +.button--var_primary {
А почему нужно использовать булевый модификатор? Тогда кнопке можно будет задать одновременно button_primary и button_secondary...

2023-09-22 13:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--var_primary {
что значит "булевый"?)
есть стандартный способ описывать модификаторы. В JS это будет компонент с интерфейсом, в котором можно выбрать одну из доступных опций - primary | secondary | alternate, я не вижу никаких проблем, одновременно primary + secondary быть не может)

2023-09-22 14:25 UTC, alexey-ryabkov commented on 03-lection1/01-button/button.css
> +.button--var_primary {
Булевый признак, например, button--disabled, как в доках [https://ru.bem.info/methodology/quick-start/#булевый](https://ru.bem.info/methodology/quick-start/#булевый) - т.е. либо disabled либо нет. 

Отделяю модификатор через двойной дефис (описывал в components/README.md). button--var_primary, где var = "variant", это модификатор типа ключ/значение для вариантов кнопки со значениями primary, secondary, alternate. 

Сделаю тогда отдельные button--primary, button--secondary, button--alternate, просто думал ключ-значение больше подходит.

2023-09-25 07:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--var_primary {
да нет, есть общий принцип описания класса модификатора, не стоит так усложнять, причем в такой форме записи мы как будто миксуем 2 способа описать модификатор - `--` и `_`

2023-09-25 07:45 UTC, GSemikozov requested changes

2023-09-25 07:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
ширину не нужно фиксировать

2023-09-25 07:45 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 2px 8px;
не исправлено (`15 15 14`)

2023-09-25 08:22 UTC, alexey-ryabkov commented on 03-lection1/01-button/button.css
> +.button--var_primary {
Понравился формат, используемый здесь https://habr.com/ru/articles/305548/ - someBlock__someElement--modificator, получается более наглядное, на мой взгляд, разделение элемента и модификатора. Но решил, чтоб не путать, переделаю на стандарт по умолчанию - понимаю, что если каждый студент будет изобретать свой формат, то проверять такое будет геммор)

2023-09-25 08:25 UTC, alexey-ryabkov commented on 03-lection1/01-button/button.css
> +  padding: 2px 8px;
Здесь и выше не было правок, ждал ответа по комменту с БЭМ, сейчас коммит с правкой запушил

2023-09-25 21:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button--var_primary {
да, то тогда вот эта штука button--var_primary превратилась бы в button--primary и не было бы вопросов)

2023-09-27 19:58 UTC, GSemikozov approved these changes

2023-09-27 19:58 UTC, merged