Add cards to the mainpage
js-tasks-ru/htmlcss-20230911-4_xelaris pull request #8
Opened 2023-09-24 15:11 UTC by alexey-ryabkov

2023-09-24 15:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-24 15:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 07:42 UTC, GSemikozov requested changes

2023-09-25 07:42 UTC, GSemikozov commented on components/page/page.css
> +html,
это глобальные стили, унесем в main.css

2023-09-25 21:32 UTC, GSemikozov approved these changes, later dismissed

2023-09-25 21:32 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-09-27 20:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-27 20:49 UTC, GSemikozov approved these changes

2023-09-27 20:49 UTC, merged