Add histogram component
js-tasks-ru/htmlcss-20230911-4_xelaris pull request #9
Opened 2023-09-24 19:34 UTC by alexey-ryabkov

2023-09-24 19:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-25 07:48 UTC, GSemikozov requested changes

2023-09-25 07:48 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  padding: 15px 25px 25px;
16 24

2023-09-25 07:48 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-top: 5px;
3

2023-09-25 07:48 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-top: 40px;
39

2023-09-25 21:32 UTC, GSemikozov approved these changes

2023-09-25 21:32 UTC, merged